### ISSUE TITLE
Not working on Safari iOS

### ISSUE THREAD

**Issue by buesing** [rafrex/fscreen#10]
iOS version 10.3.3
Safari version 10.0

As soon as I click the fullscreen button, I get this error:

`TypeError: element[vendor[key.requestFullscreen]] is not a function. (In 'element[vendor[key.requestFullscreen]]()', 'element[vendor[key.requestFullscreen]]' is undefined)
`

This is my code, I don't believe there's something wrong with it:
```
  requestFullScreen = () => {
    fscreen.requestFullscreen(this.videoRef); // this.videoRef is a reference to the video element
  }
```

**Comment by buesing** [comment]
Sorry, I'm stupid, fullscreen API is not supported on iOS.

**Comment by bjabu** [comment]
Now it is!

**Comment by jaaabir** [comment]
@bjabu i am still getting that error , i tried it in ios

**Comment by rafgraph** [comment]
The full screen api is supported by iPads but not iPhones.

**Comment by squalvj** [comment]
tested on iOS, still not support
