### ISSUE TITLE
Provide indication of fullscreen support

### ISSUE THREAD

**Issue by tmcw** [rafrex/fscreen#12]
This module knows when it can't request or use fullscreen - when vendor is `[]`, but it doesn't expose that value anywhere that a consumer can use. It'd be excellent to expose fullscreen availability.

**Comment by rafrex** [comment]
`fscreen.fullscreenEnabled` should be `false` when vendor is `[]`. Does this not work for you?

**Comment by tmcw** [comment]
Wow, how did I miss that 🤦‍♂️ thanks!
