### ISSUE TITLE
how to trigger full screen mode after a screen orientation change

### ISSUE THREAD

**Issue by StarNeit** [rafrex/fscreen#17]
#hello.
I want my website to trigger full screen mode after a screen orientation change.
But, it says that it requires user gesture.

can you please let me know how to trigger full screen when a device orientation change?
thank you.

**Comment by RonnyO** [comment]
Hey,
for modern browsers, you can use the `screen.orientation.addEventListener('change', goFullScreenHere);` and from that handler you could go fullscreen and it's considered a user gesture.

For iOS and specifically iPhones you don't have that API, but it does work from the regular `orientationchange` event if you want to go fullscreen from a video tag.
