### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by AlsDevShack** [rafrex/fscreen#26]
I'm having issues using this in Safari. 

Upon analysis it seems the CSS styles are not getting applied to the full screen elements like they do in other browsers.

i.e. in chrome when I go full screen with an element, the element get's this style applied:

```
:not(:root):fullscreen {
    object-fit: contain;
    position: fixed !important;
    top: 0px !important;
    right: 0px !important;
    bottom: 0px !important;
    left: 0px !important;
    box-sizing: border-box !important;
    min-width: 0px !important;
    max-width: none !important;
    min-height: 0px !important;
    max-height: none !important;
    width: 100% !important;
    height: 100% !important;
    transform: none !important;
    margin: 0px !important;
}
```

On Safari the element doesn't get the above styles and therefore the div isn't properly positioned on the screen, although browser does go full screen. Any suggestions for fixing, working around this?

EDIT: fixed by applying the same style to the :-webkit-full-screen pseudoelement.

I.e. I added the following to my stylesheet:

```
:not(:root):-webkit-full-screen {
  object-fit: contain;
  position: fixed !important;
  top: 0px !important;
  right: 0px !important;
  bottom: 0px !important;
  left: 0px !important;
  box-sizing: border-box !important;
  min-width: 0px !important;
  max-width: none !important;
  min-height: 0px !important;
  max-height: none !important;
  width: 100% !important;
  height: 100% !important;
  transform: none !important;
  margin: 0px !important;
}
```

**Comment by rafgraph** [comment]
Looks like you solved it, great!
