### ISSUE TITLE
Fscreen block dialog to open

### ISSUE THREAD

**Issue by nicgirault** [rafrex/fscreen#4]
hello!

I develop a React app with material-ui. The material-ui dialog does not appear in fullscreen mode when using fscreen. When I don't use fscreen to switch to fullscreen mode, the dialog open

**Comment by rafrex** [comment]
Hi, I'm not sure what's causing this, fscreen just calls the vendor prefixed enter/exit fullscreen functions. Once in fullscreen mode there shouldn't be any difference.

If you can provide a failing example I'd be happy to take a look at it. You can clone the example site in the `gh-pages` branch and add the failing example to it, or create a failing example however you see fit. Thanks.

**Comment by rafrex** [comment]
Hi closing this for now. If you're still having this issue please provide a failing example that I can debug. Thanks.
