### ISSUE TITLE
prefixing: what about Samsung SmartTV browsers?

### ISSUE THREAD

**Issue by corradocampisano** [rafrex/fscreen#5]
Hello,

as I red on the [docs](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API), "your function may vary", depending on the browser version.

I've got a couple different Samsung SmartTV, on which I'd like to have fullscreen for videos: I've got mixed results and found little docs about these browsers, so I'm sharing my findings.

With the script below, I was able to make it work on the older model (F5500), while it doesn't on the newer (ES6710), while the sample page of fscreen couldn't get none of the two on fullscreen.

I'm attaching relevant screenshots, any plan to support such browsers?

`
function setupPlayer(fullScrBtn) {
	
	var isFullscreenAvailable = document.fullscreenEnabled
	|| document.mozFullScreenEnabled || document.webkitFullscreenEnabled
	|| document.msFullscreenEnabled || false;
	
	if (isFullscreenAvailable) {

		var myEvent = function(e) {
			var fullscreenElement = document.fullscreenElement
					|| document.mozFullScreenElement
					|| document.webkitFullscreenElement
					|| document.msFullscreenElement;
			if (fullscreenElement) {
				// we are now on fullscreen
			} else {
				// we have exit fullscreen mode
			}
		};

		// add event listeners

		// W3C standard
		document.addEventListener('fullscreenchange', myEvent, false);
		// Firefox 10+, Firefox for Android
		document.addEventListener('mozfullscreenchange', myEvent, false);
		// Chrome 15+, Safari 5.1+, Opera 15+, Chrome for Android, Opera Mobile
		// 16+
		document.addEventListener('webkitfullscreenchange', myEvent, false);
		// IE 11+
		document.addEventListener('MSFullscreenChange', myEvent, false);

		// enable button
		// alert(fullScrBtn.disabled);
		fullScrBtn.disabled = false;
		// alert(fullScrBtn.disabled);
	}
}

function requestFullScreen(element) {

	var el = element || document.documentElement;

	var fullscreenElement = document.fullscreenElement
			|| document.mozFullScreenElement
			|| document.webkitFullscreenElement || document.msFullscreenElement;

	if (fullscreenElement) {
		if (document.exitFullscreen) {
			// W3C standard
			document.exitFullscreen();
		} else if (document.mozCancelFullScreen) {
			// Firefox 10+, Firefox for Android
			document.mozCancelFullScreen();
		} else if (document.webkitExitFullscreen) {
			// Chrome 20+, Safari 6+, Opera 15+, Chrome for Android, Opera
			// Mobile 16+
			document.webkitExitFullscreen();
		} else if (document.webkitCancelFullScreen) {
			// Chrome 15+, Safari 5.1+
			document.webkitCancelFullScreen();
		} else if (document.msExitFullscreen) {
			// IE 11+
			document.msExitFullscreen();
		}

	} else {

		if (el.requestFullscreen) {
			// W3C standard
			el.requestFullscreen();
		} else if (el.mozRequestFullScreen) {
			// Firefox 10+, Firefox for Android
			el.mozRequestFullScreen();
		} else if (el.msRequestFullscreen) {
			// IE 11+
			el.msRequestFullscreen();
		} else if (el.webkitRequestFullscreen) {
			if (navigator.userAgent.indexOf('Safari') != -1
					&& navigator.userAgent.indexOf('Chrome') == -1) {
				// Safari 6+
				el.webkitRequestFullscreen();
			} else {
				// Chrome 20+, Opera 15+, Chrome for Android, Opera Mobile 16+
				el.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
			}
		} else if (el.webkitRequestFullScreen) {
			if (navigator.userAgent.indexOf('Safari') != -1
					&& navigator.userAgent.indexOf('Chrome') == -1) {
				// Safari 5.1+
				el.webkitRequestFullScreen();
			} else {
				// Chrome 15+
				el.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT);
			}
		}
	}
}
...
`

**ue46es6710 - 1 - tv tag**

![ue46es6710 - 1 - tv tag](https://user-images.githubusercontent.com/25619972/30551486-e2e1336a-9c9a-11e7-8546-277d27266324.jpg)

**ue46es6710 - 2 - browser name**

![ue46es6710 - 2 - browser name](https://user-images.githubusercontent.com/25619972/30551494-e30b16f8-9c9a-11e7-82bf-24491c9a38cf.jpg)

**ue46es6710 - 3 - support prefixed**

![ue46es6710 - 3 - support prefixed](https://user-images.githubusercontent.com/25619972/30551493-e306db9c-9c9a-11e7-8881-375be2d57297.jpg)

**ue46es6710 - 4 - fscreen failing**

![ue46es6710 - 4 - fscreen failing](https://user-images.githubusercontent.com/25619972/30551488-e2e816bc-9c9a-11e7-90b5-5850284abad2.jpg)

**ue46es6710 - 5 - fullscreen disabled**

![ue46es6710 - 5 - fullscreen disabled](https://user-images.githubusercontent.com/25619972/30551487-e2e479c6-9c9a-11e7-8784-949805b77e5c.jpg)

**ue46f5500 - 1- tv tag**

![ue46f5500 - 1- tv tag](https://user-images.githubusercontent.com/25619972/30551489-e2ea8f00-9c9a-11e7-8056-0f31c0241020.jpg)

**ue46f5500 - 2 - browser name**

![ue46f5500 - 2 - browser name](https://user-images.githubusercontent.com/25619972/30551501-e9fe0416-9c9a-11e7-959e-cabfa8591516.jpg)

**ue46f5500 - 3 - support prefixed**

![ue46f5500 - 3 - support prefixed](https://user-images.githubusercontent.com/25619972/30551492-e300cfd6-9c9a-11e7-9152-d71861a3946c.jpg)

**ue46f5500 - 4 - fscreen failing**

![ue46f5500 - 4 - fscreen failing](https://user-images.githubusercontent.com/25619972/30551490-e2ef5b34-9c9a-11e7-8fff-282dc3564ae2.jpg)

**ue46f5500 - 5 - fullscreen enabled**

![ue46f5500 - 5 - fullscreen enabled](https://user-images.githubusercontent.com/25619972/30551491-e2f0ec88-9c9a-11e7-9fb1-ba1ad6c0e123.jpg)

**ue46f5500 - 6 - fullscreen working**

![ue46f5500 - 6 - fullscreen working](https://user-images.githubusercontent.com/25619972/30551505-eb68c2f0-9c9a-11e7-9296-5d3df04ee619.jpg)

**Comment by corradocampisano** [comment]
forgot to mention: on a regular browser Fscreen works fine, see shots

![screenshot from 2017-09-18 18-18-39](https://user-images.githubusercontent.com/25619972/30551921-7e761f2e-9c9c-11e7-9bf6-e66c86d77a15.png)
![screenshot from 2017-09-18 18-18-36](https://user-images.githubusercontent.com/25619972/30551922-7e7ab368-9c9c-11e7-8fd6-9a549e17deea.png)

**Comment by rafrex** [comment]
Hi, I don't have have time to support Sumsung SmartTVs in this library, however, I'd be happy to accept a pull request.

With regards to the code, it looks like it does almost the exact same thing as `fscreen`. One main difference is that it uses `document.documentElement` if no element is provided. The `fscreen` example site uses the root `div` as the fullscreen element, but `fscreen` will work with any element you give it. Also, in your pictured example, the element you're making fullscreen is a `video`.

Have you tried using `fscreen` with a `video` element, or with `document.documentElement` on your SmartTV? It wouldn't surprise me if the Samsung browser restricts which elements can go fullscreen.

**Comment by corradocampisano** [comment]
Hi rafrex
thx for the reply, my intention was to help spread support to those devices.

looks like the browser (when used standalone) has limitations, even web-apps (samsung tv apps, web based) are restricted to 960x540 (I tried larger and had to scroll):
http://developer.samsung.com/tv/develop/legacy-platform-library/tut00055/index#Creating-the-Basic-Application

in addition, on the "full-screen-working" TV, there was no way to get back to normal view (only the "enter" event was available!), so I switched to a non-web TV app, see shot

![2017-09-25 - tv apps](https://user-images.githubusercontent.com/25619972/30830615-d92806e6-a244-11e7-86d5-9813e4a8a82b.png)

cheers
.k.
