### ISSUE TITLE
wondering why fullscreen events aren't thrown when user uses menu commands to enter full screen

### ISSUE THREAD

**Issue by stepheneb** [rafrex/fscreen#7]
Full screen state isn't detected on Chrome and Firefox when entering full screen mode by using a menu UI.

This isn't actually a bug in fscreen -- seems to be an issue in the browsers.

In Chrome on a Mac you can toggle full screen in the view menu or use ctrl-command-F. 

In Chrome on Windows select the rectangle at the right-hand edge of the Zoom menu option.

http://fscreen.rafrex.com/ doesn't detect this change. It's also not reflected in:

``` document.webkitFullscreenElement => null ```

It seems some event should be thrown when this happens -- but I can't find any doc describing this alternate path to full screen.

**Comment by GrosSacASac** [comment]
in ff it F11 key enables almost fullscreen, there's 1 px at the top if you hover the ui shows up, so it is not exactly the same

**Comment by rafrex** [comment]
Hi, the type of fullscreen you are referencing is different - you're talking about making the browser app itself fullscreen, not the website, and I am not aware of anyway to pick up on those events. I suggest you open issues with the respective browsers.

Note that when the browser app is fullscreen you can still have the website enter/exit fullscreen while the browser app remains in its fullscreen mode, and `fscreen` works correctly in this scenario.
