### ISSUE TITLE
Unable to zoom in mobile browsers when in full screen.

### ISSUE THREAD

**Issue by agnelvishal** [rafrex/fscreen#9]
For example when I use chrome in android and load https://mdn.mozillademos.org/en-US/docs/Web/CSS/:fullscreen$samples/Example?revision=1312011 I am able to zoom without full screen but not in full screen. 
Not a problem with fscreen to full screen api itself

**Comment by rafrex** [comment]
I would suggest opening an issue with Android or the browsers as they is nothing I can do about this.
